"""Add capacity field to Room model

Revision ID: 358db374f8c2
Revises: 
Create Date: 2025-06-01 23:29:30.285321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358db374f8c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
